Initialization

In [41]:
import numpy as np
np.random.seed(42)

Question 1

In [42]:
mean = 50
std = 12
size = (1000,5)
A = np.random.normal(mean, std, size)


In [43]:
print("Shape: ", A.shape)
print("DataType: ", A.dtype)
print("Memory: ", A.nbytes, "bytes")

Shape:  (1000, 5)
DataType:  float64
Memory:  40000 bytes


In [44]:
A=A.astype(np.float32)
print("Memory: ", A.nbytes, "bytes")

Memory:  20000 bytes


Question 2

In [45]:
A.mean(axis=0)

array([50.01561 , 49.793495, 50.054493, 50.078407, 50.394142],
      dtype=float32)

In [46]:
A.std(axis=0)

array([11.984634 , 12.344798 , 12.0578165, 11.512342 , 11.860091 ],
      dtype=float32)

In [47]:
A_std = (A-A.mean(axis=0))/A.std(axis=0)

In [48]:
print(A_std.mean(axis=0).round(6))
print(A_std.std(axis=0).round(6))

[-4.e-06  2.e-06  2.e-06 -3.e-06  0.e+00]
[0.999999 1.       1.       1.       1.      ]


Question 3

In [49]:
def minmax(A,axis):
    min = A.min(axis=axis,keepdims=True)
    max = A.max(axis=axis,keepdims=True)
    return (A-min)/(max-min)

In [50]:
A_0 = minmax(A,axis=0)
print(A_0.min(axis=0))
print(A_0.max(axis=0))  

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [51]:
A_1 = minmax(A,axis=1)
print(A_1.min(axis=1))
print(A_1.max(axis=1))  

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

Question 4

In [52]:
mask = np.random.random(size=A.shape) < 0.05
mask

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       ...,
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False]], shape=(1000, 5))

In [53]:
A[mask] = np.nan
A

array([[55.96057 , 48.340828, 57.772263, 68.27636 , 47.19016 ],
       [47.190357, 68.950554, 59.209217, 44.366306, 56.51072 ],
       [44.438988, 44.411243, 52.903545, 27.040638,       nan],
       ...,
       [69.62957 , 47.347492,       nan, 52.311165, 78.705315],
       [24.807724, 58.198677, 48.62237 ,       nan, 42.11153 ],
       [49.41242 , 58.536926, 87.35492 , 59.696434, 39.82321 ]],
      shape=(1000, 5), dtype=float32)

In [54]:
col_means = np.nanmean(A, axis=0)

nan_mask = np.isnan(A)
row, col = np.where(nan_mask)

A[nan_mask] = col_means[col]
np.isnan(A).sum() == 0

np.True_

Question 5

In [55]:
col_means = A.mean(axis=0)
col_stds = A.std(axis=0)

In [56]:
outlier_mask = np.abs(A - col_means) > 3 * col_stds

In [57]:
print(outlier_mask.sum(axis=0))

[5 1 5 3 5]


In [58]:
col_medians = np.median(A, axis=0)

In [59]:
_, outlier_cols = np.where(outlier_mask)
A[outlier_mask] = col_medians[outlier_cols]
A

array([[55.96057 , 48.340828, 57.772263, 68.27636 , 47.19016 ],
       [47.190357, 68.950554, 59.209217, 44.366306, 56.51072 ],
       [44.438988, 44.411243, 52.903545, 27.040638, 50.355904],
       ...,
       [69.62957 , 47.347492, 49.88762 , 52.311165, 78.705315],
       [24.807724, 58.198677, 48.62237 , 50.254612, 42.11153 ],
       [49.41242 , 58.536926, 49.88762 , 59.696434, 39.82321 ]],
      shape=(1000, 5), dtype=float32)

Question 6

In [60]:
X = A[:200]
X1 = X[:,None,:]
X2 = X[None,:,:]

In [61]:
X_diff = X1 - X2
X_diff.shape

(200, 200, 5)

In [62]:
dist = np.sqrt(np.sum(X_diff**2, axis=2))
dist

array([[ 0.       , 34.092606 , 43.38548  , ..., 35.184258 , 37.86796  ,
        36.770718 ],
       [34.092606 ,  0.       , 31.425623 , ..., 13.143729 , 49.135822 ,
         3.3343363],
       [43.38548  , 31.425623 ,  0.       , ..., 33.1428   , 28.784973 ,
        32.668663 ],
       ...,
       [35.184258 , 13.143729 , 33.1428   , ...,  0.       , 49.434933 ,
        13.852467 ],
       [37.86796  , 49.135822 , 28.784973 , ..., 49.434933 ,  0.       ,
        51.277668 ],
       [36.770718 ,  3.3343363, 32.668663 , ..., 13.852467 , 51.277668 ,
         0.       ]], shape=(200, 200), dtype=float32)

In [63]:
print(np.allclose(np.diag(dist), 0))
print(np.allclose(dist, dist.T))

True
True


Question 7

In [64]:
np.fill_diagonal(dist, np.inf)

In [65]:
nearest = np.argpartition(dist, kth=4, axis=1)[:, :5]
nearest.shape

(200, 5)

Question 8

In [66]:
%%time
values = np.random.randint(0, 100,size=1_000_000)
counts_numpy = np.bincount(values, minlength=100)

CPU times: total: 15.6 ms
Wall time: 17.2 ms


In [67]:
%%time
counts_python = [0] * 100
for v in values:
    counts_python[v] += 1

CPU times: total: 203 ms
Wall time: 198 ms


Question 9

In [69]:
from numpy.lib.stride_tricks import sliding_window_view

In [ ]:
data = np.random.randint(0, 100, size=10000)
data

array([21, 72, 99, ..., 48,  7, 30], shape=(10000,), dtype=int32)

In [70]:
windows = sliding_window_view(data, 10)
print(windows.shape)

(9991, 10)


In [71]:
windows_mean = windows.mean(axis=1)
windows_mean.shape

(9991,)

In [74]:
import pandas as pd
pd_means = pd.Series(data).rolling(10).mean()
print(np.allclose(windows_mean, pd_means[9:].to_numpy()))

True


Question 10

In [78]:
new = np.random.randint(0, 100, size=(12,8))
new = new.reshape(4,3,8)
new.shape


(4, 3, 8)

In [81]:
result = new.mean(axis=1)
result.shape

(4, 8)

Question 11

In [ ]:
np.save('clean.npy',A)

In [83]:
loaded = np.load("clean.npy")
assert np.array_equal(loaded, A)